"use client";
import { ParallaxScroll } from "../../../components/ui/parallax-scroll";

export function ParallaxScrollSecondDemo({ className, gridClassName }: { className?: string; gridClassName?: string }) {
  return <ParallaxScroll images={images} className={className} gridClassName={gridClassName} />;
}

const images = [
    "https://gamma.app/_next/static/media/_THE-SUNDAY-CLUB.6d70b96d.jpg",
    "https://gamma.app/_next/static/media/1_.a2ef107c.jpg",
    "https://gamma.app/_next/static/media/1_PISTA-NG-PAGKAING-PINOY.2f7024d5.jpg",
    "https://gamma.app/_next/static/media/1_SOURCE.a7a0ada4.jpg",
    "https://gamma.app/_next/static/media/1_YUNA-KASUMI.fb962749.jpg",
    "https://gamma.app/_next/static/media/3D-Modeling-Presentation.dde77dcf.jpg",
    "https://gamma.app/_next/static/media/7.808f9436.jpg",
    "https://gamma.app/_next/static/media/8.017d9112.jpg",
    "https://gamma.app/_next/static/media/9.da0a88e2.jpg",
    "https://gamma.app/_next/static/media/11.421b66f8.jpg",
    "https://gamma.app/_next/static/media/12.6a57fd26.jpg",
    "https://gamma.app/_next/static/media/13.730998c3.jpg",
    "https://gamma.app/_next/static/media/21.fc3a65b3.jpg",
    "https://gamma.app/_next/static/media/24.e839ee01.jpg",
    "https://gamma.app/_next/static/media/25.f04d189f.jpg",
    "https://gamma.app/_next/static/media/26.311a8e19.jpg",
    "https://gamma.app/_next/static/media/27.ddc0a653.jpg",
    "https://gamma.app/_next/static/media/30.0912dcd7.jpg",
    "https://gamma.app/_next/static/media/AI-Model-Launch.c2aac47e.jpg",
    "https://gamma.app/_next/static/media/Brand-Design-Brief-Presentation.ad5491ba.jpg",
    "https://gamma.app/_next/static/media/Brand-Mood-Board-IG-Story.207b3c46.jpg",
    "https://gamma.app/_next/static/media/Cara-New-Collection-Teaser.ebf96b25.jpg",
    "https://gamma.app/_next/static/media/COASTAL-CALM.72192363.jpg",
    "https://gamma.app/_next/static/media/Company-Review-Presentation.ddcf2247.jpg",
    "https://gamma.app/_next/static/media/Concept-Proposal-Presentation.3d1a79f9.jpg",
    "https://gamma.app/_next/static/media/Content-Marketing-Social-Media-Post.39f1e821.jpg",
    "https://gamma.app/_next/static/media/Creative-Strategy-Presentation.425fa621.jpg",
    "https://gamma.app/_next/static/media/Design-Conversion-Funnel-Infographics.24a5f608.jpg",
    "https://gamma.app/_next/static/media/Five-Most-Affordable-iPads-Infographics.d2c17938.jpg",
    "https://gamma.app/_next/static/media/How-to-Improve-Your-Mental-Well-Being-Infographics.1db66178.jpg",
    "https://gamma.app/_next/static/media/Interior-Design-Collection-Presentation.3692d172.jpg",
    "https://gamma.app/_next/static/media/Interior-Design-Lesson-Presentation.16a87ec3.jpg",
    "https://gamma.app/_next/static/media/Interior-Design-Presentation.437bce18.jpg",
    "https://gamma.app/_next/static/media/Launch-Teaser-Presentation.1b86bec6.jpg",
    "https://gamma.app/_next/static/media/Luxury-Clothing-Presentation.ddbd5c0c.jpg",
    "https://gamma.app/_next/static/media/Management-Report-Financial-Risk-Infographics.b7b15b5c.jpg",
    "https://gamma.app/_next/static/media/Marketing-Report-Presentation.36852b92.jpg",
    "https://gamma.app/_next/static/media/New-Podcast-Alert-Social-Media-Post.a61a9ff4.jpg",
    "https://gamma.app/_next/static/media/nin59uiulbf6j6o.1f647b9c.jpg",
    "https://gamma.app/_next/static/media/Pitch-Deck.033be8f9.jpg",
    "https://gamma.app/_next/static/media/Productivity-Tip-Social-Media-Post.9dcd423a.jpg",
    "https://gamma.app/_next/static/media/Quirky-Portfolio-Testimonial-Presentation.535be223.jpg",
    "https://gamma.app/_next/static/media/Silver-Jewelry-Social-Media-Post.faf95200.jpg",
    "https://gamma.app/_next/static/media/Skincare-Brand-Post.d09688ea.jpg",
    "https://gamma.app/_next/static/media/Sustainable-Living-Tips-Social-Media-Post.e1524b92.jpg",
    "https://gamma.app/_next/static/media/Tech-App-Launch-2-Presentation.562d0f8a.jpg",
    "https://gamma.app/_next/static/media/Tech-App-Launch-Presentation.31c5cff2.jpg",
    "https://gamma.app/_next/static/media/Tech-Product-Launch-Presentation.651662ff.jpg",
    "https://gamma.app/_next/static/media/The-Business-Timeline-Infographics.798567a7.jpg",
    "https://gamma.app/_next/static/media/Trattoria-Italian-Resto-IG-Story.b0884ce4.jpg",
    "https://gamma.app/_next/static/media/lh-wmuaabWd-mSr-lqdym-4-1.b43bf2b0.jpg",
    "https://gamma.app/_next/static/media/lmqblt-llbnny-lmshhwr-1.1fa0d527.jpg"
  ];